server:
  port: 8080
spring:
  application:
    name: aws-project01
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
